# Site settings
baseurl = "http://airmusic.github.io/"
languageCode = "en-us"
title = "Happyi"
theme = "hyde"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	
	name = "Happyyi"
	description = "一个普通的程序员"


